const cardsContainer = document.getElementById("adminCardsList");
const FIRESTORE_SECTIONS = new Set(["announcements", "quickCards", "forms", "services", "policies", "adminCards"]);
let DATA = { quickCards: [], forms: [], services: [], announcements: [], adminCards: [], policies: [] };
let currentEditSection = null;
let currentEditKeyValue = null;
let firestoreAnnouncementsReady = false;

const esc = value => String(value ?? "").replace(/[&<>"']/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[char]));
const toBool = value => value === true || ["true", "1", "yes", "y", "نعم"].includes(String(value ?? "").trim().toLowerCase());
const toNum = (value, fallback = 9999) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const slugify = value => String(value || "").trim().toLowerCase().replace(/[^a-z0-9_-]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || `item-${Date.now()}`;
const isValidLinkValue = value => !String(value || "").trim() || /^(?:https?:\/\/|mailto:)/i.test(value) || ["#home", "#announcements", "#forms", "#quickAccess", "#policies", "#info", "#employeeGuide", "index.html", "index.html#announcements", "index.html#forms", "index.html#policies", "index.html#info"].includes(String(value).trim());

const SECTION_META = {
  quickCards: { title: "كرت سريع", keyField: "quickKey", titleField: "title", listId: "quickCardsManageList", fields: [
    { key:"quickKey", label:"المفتاح الفريد (بالإنكليزية، بدون مسافات)", type:"text", required:true }, { key:"title", label:"العنوان", type:"text", required:true }, { key:"description", label:"الوصف المختصر", type:"text" }, { key:"icon", label:"الأيقونة (إيموجي)", type:"text" }, { key:"href", label:"الرابط", type:"text", required:true, isLink:true }, { key:"badge", label:"الشارة", type:"select", options:["", "جديد", "مهم", "محدث"] }, { key:"size", label:"الحجم", type:"select", options:["", "small", "medium", "large", "wide"] }, { key:"sortOrder", label:"ترتيب الظهور", type:"number" }, { key:"isActive", label:"نشط", type:"status" }
  ] },
  forms: { title: "نموذج", keyField: "formKey", titleField: "title", listId: "formsManageList", fields: [
    { key:"formKey", label:"المفتاح الفريد (بالإنكليزية، بدون مسافات)", type:"text", required:true }, { key:"title", label:"اسم النموذج", type:"text", required:true }, { key:"subtitle", label:"وصف مختصر", type:"text" }, { key:"description", label:"وصف النموذج الكامل", type:"textarea" }, { key:"icon", label:"الأيقونة (إيموجي)", type:"text" }, { key:"badge", label:"شارة التصنيف", type:"text" }, { key:"linkText", label:"نص الزر", type:"text" }, { key:"linkUrl", label:"رابط النموذج", type:"text", required:true, isLink:true }, { key:"size", label:"حجم الكرت", type:"select", options:["", "small", "medium", "large", "wide"] }, { key:"sortOrder", label:"ترتيب الظهور", type:"number" }, { key:"isActive", label:"حالة الظهور", type:"status" }
  ] },
  announcements: { title: "إعلان", keyField: "id", titleField: "title", listId: "announcementsManageList", fields: [
    { key:"id", label:"معرف فريد", type:"text", required:true }, { key:"title", label:"عنوان الإعلان", type:"text", required:true }, { key:"body", label:"نص الإعلان", type:"textarea" }, { key:"tag", label:"الوسم", type:"text" }, { key:"date", label:"تاريخ البداية", type:"date" }, { key:"endDate", label:"تاريخ النهاية", type:"date" }, { key:"linkText", label:"نص الرابط", type:"text" }, { key:"linkUrl", label:"رابط التفاصيل", type:"text", isLink:true }, { key:"priority", label:"الأهمية", type:"number" }, { key:"isActive", label:"حالة الظهور", type:"status" }
  ] },
  services: { title: "خدمة", keyField: "serviceKey", titleField: "title", listId: "servicesManageList", fields: [
    { key:"serviceKey", label:"المفتاح الفريد", type:"text", required:true }, { key:"title", label:"اسم الخدمة", type:"text", required:true }, { key:"subtitle", label:"وصف مختصر", type:"text" }, { key:"description", label:"الوصف الكامل", type:"textarea" }, { key:"tag", label:"التصنيف", type:"text" }, { key:"linkText", label:"نص الزر", type:"text" }, { key:"linkUrl", label:"رابط الخدمة", type:"text", required:true, isLink:true }, { key:"size", label:"حجم البطاقة", type:"select", options:["", "small", "medium", "large", "wide"] }, { key:"sortOrder", label:"ترتيب الظهور", type:"number" }, { key:"isActive", label:"حالة الظهور", type:"status" }
  ] },
  policies: { title: "سياسة", keyField: "policyKey", titleField: "title", listId: "policiesManageList", activeField:"active", orderField:"order", fields: [
    { key:"policyKey", label:"المفتاح الفريد (بالإنكليزية، بدون مسافات)", type:"text", required:true }, { key:"title", label:"اسم السياسة أو اللائحة", type:"text", required:true }, { key:"description", label:"الوصف الرسمي", type:"textarea" }, { key:"fileUrl", label:"رابط ملف السياسة", type:"text", required:true, isLink:true }, { key:"icon", label:"الأيقونة (إيموجي)", type:"text" }, { key:"version", label:"رقم الإصدار", type:"text" }, { key:"updatedDate", label:"تاريخ آخر تحديث", type:"date" }, { key:"order", label:"ترتيب الظهور", type:"number" }, { key:"active", label:"حالة الظهور", type:"status", default:true }, { key:"buttonText", label:"نص زر العرض", type:"text", default:"عرض السياسة" }
  ] },
  adminCards: { title: "بطاقة إدارية", keyField: "adminKey", titleField: "title", listId: "adminCardsManageList", fields: [
    { key:"adminKey", label:"المفتاح الفريد", type:"text", required:true }, { key:"title", label:"عنوان البطاقة", type:"text", required:true }, { key:"description", label:"الوصف", type:"textarea" }, { key:"tag", label:"التصنيف", type:"text" }, { key:"linkText", label:"نص الزر", type:"text" }, { key:"linkUrl", label:"الرابط", type:"text", isLink:true }, { key:"size", label:"حجم البطاقة", type:"select", options:["", "small", "medium", "large", "wide"] }, { key:"sortOrder", label:"ترتيب الظهور", type:"number" }, { key:"isActive", label:"نشط", type:"status" }
  ] }
};

const listFilters = Object.fromEntries(Object.keys(SECTION_META).map(section => [section, { q:"", status:"all" }]));

function showStatus(message, type = "success") { const node = document.getElementById("cmsStatusBanner"); if (node) { node.textContent = message; node.className = `cms-status-banner ${type}`; node.hidden = false; } showAdminToast(message, type); }
function renderDashboard() { const set = (id, value) => { const node = document.getElementById(id); if (node) node.textContent = String(value); }; set("statQuickCards", DATA.quickCards.length); set("statForms", DATA.forms.length); set("statAnnouncements", DATA.announcements.length); set("statPoliciesActive", DATA.policies.filter(item => toBool(item.active ?? item.isActive)).length); set("statPoliciesTotal", DATA.policies.length); }
function renderCards(cards) { if (!cardsContainer) return; cardsContainer.replaceChildren(); cards.filter(card => toBool(card.isActive ?? card.active ?? true)).sort((a,b) => toNum(a.sortOrder) - toNum(b.sortOrder)).forEach(card => { const item = document.createElement("article"); item.className = "admin-card"; item.innerHTML = `<div class="admin-card-tag">${esc(card.tag || "عام")}</div><h3 class="admin-card-title">${esc(card.title)}</h3><p class="admin-card-desc">${esc(card.description)}</p><div class="admin-card-actions"><a class="admin-card-btn" href="${esc(card.linkUrl || "#")}" target="_blank" rel="noopener">${esc(card.linkText || "الدخول")}</a></div>`; cardsContainer.appendChild(item); }); }
function renderManageList(section) { const meta = SECTION_META[section], container = document.getElementById(meta.listId); if (!container) return; const filter = listFilters[section]; let items = DATA[section].slice().sort((a,b) => toNum(a[meta.orderField || "sortOrder"] ?? a.priority) - toNum(b[meta.orderField || "sortOrder"] ?? b.priority)); if (filter.q) items = items.filter(item => String(item[meta.titleField] || "").toLowerCase().includes(filter.q.toLowerCase())); if (filter.status !== "all") items = items.filter(item => toBool(item[meta.activeField || "isActive"] ?? true) === (filter.status === "active")); if (!items.length) { container.innerHTML = `<div class="cms-empty"><p>لا توجد عناصر مطابقة.</p><button class="btn btn-add" type="button" onclick="openItemEditor('${section}')">+ إضافة ${esc(meta.title)} جديد</button></div>`; return; } container.innerHTML = items.map(item => { const active = toBool(item[meta.activeField || "isActive"] ?? true), key = item[meta.keyField]; return `<div class="cms-item ${active ? "" : "is-inactive"}"><div class="cms-item-info"><div class="cms-item-title">${esc(item[meta.titleField] || "بدون عنوان")}</div><div class="cms-item-meta"><span class="cms-status-pill ${active ? "active" : "inactive"}">${active ? "نشط" : "غير نشط"}</span></div></div><div class="cms-item-actions"><button class="btn btn-outline" type="button" data-action="edit" data-section="${esc(section)}" data-key="${esc(key)}">تعديل</button><button class="btn btn-dark" type="button" data-action="toggle" data-section="${esc(section)}" data-key="${esc(key)}">${active ? "إخفاء" : "إظهار"}</button><button class="btn btn-dark" type="button" data-action="delete" data-section="${esc(section)}" data-key="${esc(key)}">حذف</button></div></div>`; }).join(""); }
function renderAllManageLists() { Object.keys(SECTION_META).forEach(renderManageList); renderCards(DATA.adminCards); renderDashboard(); }

function openItemEditor(section, keyValue) { const meta = SECTION_META[section]; if (!meta) return; currentEditSection = section; currentEditKeyValue = keyValue || null; const existing = keyValue ? DATA[section].find(item => String(item[meta.keyField]) === String(keyValue)) : null; document.getElementById("itemEditTitle").textContent = existing ? `تعديل ${meta.title}` : `إضافة ${meta.title}`; document.getElementById("itemEditError").textContent = ""; document.getElementById("itemEditForm").innerHTML = meta.fields.map(field => { const value = existing?.[field.key] ?? field.default ?? (field.type === "status" ? true : ""); const disabled = existing && field.key === meta.keyField ? "disabled" : ""; if (field.type === "textarea") return `<div class="field-row"><label for="field_${field.key}">${esc(field.label)}</label><textarea id="field_${field.key}" ${disabled}>${esc(value)}</textarea></div>`; if (field.type === "select") return `<div class="field-row"><label for="field_${field.key}">${esc(field.label)}</label><select id="field_${field.key}" ${disabled}>${field.options.map(option => `<option value="${esc(option)}" ${String(value) === option ? "selected" : ""}>${esc(option || "بدون")}</option>`).join("")}</select></div>`; if (field.type === "status") return `<div class="field-row"><label for="field_${field.key}">${esc(field.label)}</label><select id="field_${field.key}"><option value="true" ${toBool(value) ? "selected" : ""}>نشط</option><option value="false" ${!toBool(value) ? "selected" : ""}>مخفي</option></select></div>`; return `<div class="field-row"><label for="field_${field.key}">${esc(field.label)}</label><input type="${field.type}" id="field_${field.key}" value="${esc(value)}" ${disabled}></div>`; }).join(""); document.getElementById("itemEditModal").classList.add("show"); document.getElementById("itemEditModal").setAttribute("aria-hidden", "false"); }
function closeItemEditor() { const modal = document.getElementById("itemEditModal"); modal.classList.remove("show"); modal.setAttribute("aria-hidden", "true"); currentEditSection = null; currentEditKeyValue = null; }
async function saveItemEditor() { const section = currentEditSection, meta = SECTION_META[section], error = document.getElementById("itemEditError"); if (!meta) return; const row = {}; for (const field of meta.fields) { const node = document.getElementById(`field_${field.key}`); if (!node) continue; row[field.key] = field.type === "status" ? node.value === "true" : field.type === "number" ? (node.value === "" ? 9999 : Number(node.value)) : node.value.trim(); } row[meta.keyField] = currentEditKeyValue || row[meta.keyField] || slugify(row[meta.titleField] || meta.title); for (const field of meta.fields) { if (field.required && !String(row[field.key] ?? "").trim()) { error.textContent = `الحقل "${field.label}" مطلوب.`; return; } if (field.isLink && !isValidLinkValue(row[field.key])) { error.textContent = `الحقل "${field.label}" يحتوي رابطاً غير صالح.`; return; } } const exists = DATA[section].some(item => String(item[meta.keyField]) === String(row[meta.keyField])); try { const api = section === "announcements" ? window.MHR_FIRESTORE_ANNOUNCEMENTS : window.MHR_FIRESTORE_CMS; if (!api) throw new Error("FIRESTORE_NOT_READY"); if (section === "announcements") { const payload = { id:row.id, title:row.title, body:row.body || "", tag:row.tag || "", date:row.date || "", endDate:row.endDate || "", linkText:row.linkText || "", linkUrl:row.linkUrl || "", priority:Number(row.priority || 9999), isActive:toBool(row.isActive) }; if (exists) await api.updateAnnouncement(payload.id, payload); else await api.createAnnouncement(payload); } else await api.saveCollectionItem(section, { ...row, id:row[meta.keyField] }, !exists); closeItemEditor(); showStatus("تم حفظ العنصر في Firestore."); } catch (_) { error.textContent = "تعذر حفظ العنصر في Firestore. لم تتغير البيانات المعروضة."; } }
async function toggleItemActive(section, keyValue) { const meta = SECTION_META[section], item = DATA[section].find(row => String(row[meta.keyField]) === String(keyValue)); if (!item) return; try { const id = item.id || item[meta.keyField], next = !toBool(item[meta.activeField || "isActive"] ?? true); if (section === "announcements") await window.MHR_FIRESTORE_ANNOUNCEMENTS?.toggleAnnouncement(id, next); else await window.MHR_FIRESTORE_CMS?.toggleCollectionItem(section, id, next); showStatus("تم تحديث العنصر في Firestore."); } catch (_) { showStatus("تعذر تحديث العنصر في Firestore.", "error"); } }
let pendingDeletion = null;
function requestDeleteItem(section, keyValue) { const meta = SECTION_META[section], item = DATA[section].find(row => String(row[meta.keyField]) === String(keyValue)); if (!item) return; pendingDeletion = { section, keyValue }; const modal = document.getElementById("deleteConfirmModal"); modal?.classList.add("show"); modal?.setAttribute("aria-hidden", "false"); document.getElementById("deleteConfirmButton")?.focus(); }
function closeDeleteConfirmation() { pendingDeletion = null; const modal = document.getElementById("deleteConfirmModal"); modal?.classList.remove("show"); modal?.setAttribute("aria-hidden", "true"); }
async function deleteItem() { if (!pendingDeletion) return; const { section, keyValue } = pendingDeletion, meta = SECTION_META[section], item = DATA[section].find(row => String(row[meta.keyField]) === String(keyValue)); if (!item) return closeDeleteConfirmation(); const button = document.getElementById("deleteConfirmButton"); button?.classList.add("is-loading"); button && (button.disabled = true); try { const id = item.id || item[meta.keyField]; if (section === "announcements") await window.MHR_FIRESTORE_ANNOUNCEMENTS?.deleteAnnouncement(id); else await window.MHR_FIRESTORE_CMS?.removeCollectionItem(section, id); closeDeleteConfirmation(); showStatus("تم حذف العنصر من Firestore."); } catch (_) { showStatus("تعذر حذف العنصر من Firestore.", "error"); } finally { button?.classList.remove("is-loading"); button && (button.disabled = false); } }
function refreshFirestoreData() { localStorage.removeItem("mhr_firestore_cms_v1"); localStorage.removeItem("mhr_firestore_announcements_v1"); window.location.reload(); }
async function logoutAdmin() { try { await window.MHR_ADMIN_AUTH?.logout(); } finally { window.location.href = "index.html"; } }
function switchTab(name) { document.querySelectorAll(".tab-panel").forEach(panel => { panel.hidden = panel.dataset.tabPanel !== name; }); document.querySelectorAll(".admin-tab-btn").forEach(button => { const active = button.dataset.tab === name; button.classList.toggle("active", active); button.setAttribute("aria-selected", active ? "true" : "false"); }); }
function initUi() { document.querySelectorAll(".admin-tab-btn").forEach(button => button.addEventListener("click", () => { switchTab(button.dataset.tab); document.body.classList.remove("sidebar-open"); document.getElementById("adminMenuToggle")?.setAttribute("aria-expanded", "false"); })); document.querySelectorAll("[data-filter-search]").forEach(input => input.addEventListener("input", () => { listFilters[input.dataset.filterSearch].q = input.value; renderManageList(input.dataset.filterSearch); })); document.querySelectorAll("[data-filter-status]").forEach(select => select.addEventListener("change", () => { listFilters[select.dataset.filterStatus].status = select.value; renderManageList(select.dataset.filterStatus); })); document.getElementById("adminMenuToggle")?.addEventListener("click", () => { const open = document.body.classList.toggle("sidebar-open"); document.getElementById("adminMenuToggle")?.setAttribute("aria-expanded", String(open)); }); document.getElementById("deleteConfirmButton")?.addEventListener("click", deleteItem); document.getElementById("deleteCancelButton")?.addEventListener("click", closeDeleteConfirmation); document.addEventListener("click", event => { const button = event.target.closest("[data-action]"); if (!button) return; const { action, section, key } = button.dataset; if (action === "edit") openItemEditor(section, key); if (action === "toggle") toggleItemActive(section, key); if (action === "delete") requestDeleteItem(section, key); }); document.addEventListener("keydown", event => { if (event.key === "Escape") { closeItemEditor(); closeDeleteConfirmation(); document.body.classList.remove("sidebar-open"); } }); }
function startFirestoreAnnouncementsAdmin() { const api = window.MHR_FIRESTORE_ANNOUNCEMENTS; if (!api || firestoreAnnouncementsReady) return; firestoreAnnouncementsReady = true; api.subscribeToAnnouncements(rows => { DATA.announcements = rows; renderManageList("announcements"); renderDashboard(); }, () => showStatus("تعذر تحميل الإعلانات من Firestore.", "error")); }
function startFirestoreCmsAdmin() { const api = window.MHR_FIRESTORE_CMS; if (!api || startFirestoreCmsAdmin.started) return; startFirestoreCmsAdmin.started = true; ["quickCards", "forms", "services", "policies", "adminCards"].forEach(section => api.subscribeCollection(section, rows => { DATA[section] = rows; renderManageList(section); renderDashboard(); }, () => showStatus("تعذر تحميل محتوى Firestore.", "error"))); }
document.addEventListener("mhr-firestore-announcements-ready", startFirestoreAnnouncementsAdmin);
document.addEventListener("mhr-firestore-cms-ready", startFirestoreCmsAdmin);
document.addEventListener("mhr-admin-auth-ready", () => { startFirestoreAnnouncementsAdmin(); startFirestoreCmsAdmin(); });
document.addEventListener("DOMContentLoaded", async () => { initUi(); renderAllManageLists(); const user = await window.MHR_ADMIN_AUTH?.waitForAuthorizedAdmin(); if (!user) { window.location.href = "index.html?adminLogin=1"; return; } startFirestoreAnnouncementsAdmin(); startFirestoreCmsAdmin(); });

function showAdminToast(message, type = "success") { const region = document.getElementById("adminToastRegion"); if (!region || !message) return; const item = document.createElement("div"); item.className = `toast ${type}`; item.textContent = message; region.appendChild(item); window.setTimeout(() => item.remove(), 4200); }
